import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Providers from "./providers";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <Providers>
        <html lang="en">
          <body
            className={`${inter.className}`}
          >
            {/* <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange> */}

            <main className="min-h-screen ">
              {children}
            </main>
            <Toaster richColors />

            {/* </ThemeProvider> */}
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
